name: {{cookiecutter.project_name}} PR Validation

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  validate:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Check PR title
      run: |
        echo "Validating PR title format"
        # Add PR title validation logic here
    
    - name: Check for required files
      run: |
        echo "Checking for required files"
        # Add file existence checks here
    
    - name: Run code quality checks
      run: |
        echo "Running code quality checks"
        # Add your linting/quality commands here
    
    - name: Check documentation updates
      run: |
        echo "Checking documentation updates"
        # Add documentation validation here
    
    - name: Validate commit messages
      run: |
        echo "Validating commit messages"
        # Add commit message validation here
    
    - name: Check for GxP compliance
      if: contains(github.head_ref, 'gxp') || contains(github.event.pull_request.labels.*.name, 'gxp')
      run: |
        echo "Running GxP compliance checks"
        # Add GxP-specific validation here