blank_issues_enabled: false
contact_links:
  - name: {{cookiecutter.project_name}} Support
    url: https://github.com/{{cookiecutter.author_name}}/{{cookiecutter.project_slug}}/discussions
    about: Please ask questions about {{cookiecutter.project_name}} here.
